export const Alphabet =[
    {'Японский':[
        {name:'hiragana',hiragana :'あ',сyrillic :"a"},
        {name:'hiragana',hiragana:'い',cyrillic :'и'},
        {name:'hiragana',hiragana:'う',cyrillic: 'у'},
        {name:'hiragana',hiragana: 'え',cyrillic:'э'}, 
        {name:'hiragana',hiragana: "お",cyrillic:"о"}, 
        {name:'hiragana',hiragana: "か",cyrillic:"ка"}, 
        {name:'hiragana',hiragana: "き",cyrillic:"ки"}, 
        {name:'hiragana',hiragana: "く",cyrillic:"ку"},
        {name:'hiragana',hiragana: "け",cyrillic:"кэ"}, 
        {name:'hiragana',hiragana: "こ",cyrillic:"ко"}, 
        {name:'hiragana',hiragana: "さ",cyrillic:"са"}, 
        {name:'hiragana',hiragana: "し",cyrillic:"си"},
        {name:'hiragana',hiragana: "す",cyrillic:"су"}, 
        {name:'hiragana',hiragana: "せ",cyrillic:"сэ"}, 
        {name:'hiragana',hiragana: "そ",cyrillic:"со"}, 
        {name:'hiragana',hiragana: "た",cyrillic:"та"},
        {name:'hiragana',hiragana: "ち",cyrillic:"ти"},
        {name:'hiragana',hiragana: "つ",cyrillic:"цу"},
        {name:'hiragana',hiragana: "て",cyrillic:"тэ"},
        {name:'hiragana',hiragana: "と",cyrillic:"то"},
        {name:'hiragana',hiragana: "な",cyrillic:"на"},
        {name:'hiragana',hiragana: "に",cyrillic:"ни"},
        {name:'hiragana',hiragana: "ぬ",cyrillic:"ну"},
        {name:'hiragana',hiragana: "ね",cyrillic:"нэ"},
        {name:'hiragana',hiragana: "の",cyrillic:"но"},
        {name:'hiragana',hiragana: "は",cyrillic:"ха"},
        {name:'hiragana',hiragana: "ひ",cyrillic:"хи"},
        {name:'hiragana',hiragana: "ふ",cyrillic:"фу"},
        {name:'hiragana',hiragana: "へ",cyrillic:"хэ"},
        {name:'hiragana',hiragana: "ほ",cyrillic:"хо"},
        {name:'hiragana',hiragana: "ま",cyrillic:"ма"},
        {name:'hiragana',hiragana: "み",cyrillic:"ми"},
        {name:'hiragana',hiragana: "む",cyrillic:"му"},
        {name:'hiragana',hiragana: "め",cyrillic:"мэ"},
        {name:'hiragana',hiragana: "も",cyrillic:"мо"},
        {name:'hiragana',hiragana: "や",cyrillic:"я"},
        {name:'hiragana',hiragana: "ゆ",cyrillic:"ю"},
        {name:'hiragana',hiragana: "よ",cyrillic:"ё"},
        {name:'hiragana',hiragana: "ら",cyrillic:"ра"},
        {name:'hiragana',hiragana: "り",cyrillic:"ри"},
        {name:'hiragana',hiragana: "る",cyrillic:"ру"},
        {name:'hiragana',hiragana: "れ",cyrillic:"рэ"},
        {name:'hiragana',hiragana: "ろ",cyrillic:"ро"},
        {name:'hiragana',hiragana: "わ",cyrillic:"ва"},
        {name:'hiragana',hiragana: "ん",cyrillic:"н"},
        {name:'hiragana',hiragana: "を",cyrillic:"во"}
        ]},
    {'Корейский':[
            {name:'hangul',hangul:'ㅏ',cyrillic:'а'},
            {name:'hangul',hangul:'ㅑ',cyrillic:'я'},
            {name:'hangul',hangul:'ㅗ',cyrillic:'о'},
            {name:'hangul',hangul:'ㅛ',cyrillic:'ё'},
            {name:'hangul',hangul:'ㅓ',cyrillic:'оэ'},
            {name:'hangul',hangul:'ㅕ',cyrillic:'йоэ'},
            {name:'hangul',hangul:'ㅜ',cyrillic:'у'},
            {name:'hangul',hangul:'ㅠ',cyrillic:'ю'},
            {name:'hangul',hangul:'ㅡ',cyrillic:'ы'},
            {name:'hangul',hangul:'ㅣ',cyrillic:'и'},
            {name:'hangul',hangul:'ㄱ',cyrillic:'к'},
            {name:'hangul',hangul:'ㄴ',cyrillic:'н'},
            {name:'hangul',hangul:'ㄷ',cyrillic:'т'},
            {name:'hangul',hangul:'ㄹ',cyrillic1:'р'},
            {name:'hangul',hangul:'ㅁ',cyrillic:'м'},
            {name:'hangul',hangul:'ㅂ',cyrillic1:'п'},
            {name:'hangul',hangul:'ㅅ',cyrillic1:'с'},
            {name:'hangul',hangul:'ㅇ',cyrillic:'н'},
            {name:'hangul',hangul:'ㅈ',cyrillic1:'ч'},
            {name:'hangul',hangul:'ㅊ',cyrillic:'чх'},
            {name:'hangul',hangul:'ㅋ',cyrillic:'кх'},
            {name:'hangul',hangul:'ㅌ',cyrillic:'тх'},
            {name:'hangul',hangul:'ㅍ',cyrillic:'пх'},
            {name:'hangul',hangul:'ㅎ',cyrillic:'х'},
            {name:'hangul',hangul:'ㄲ',cyrillic:'к'},
            {name:'hangul',hangul:'ㄸ',cyrillic:'т'},
            {name:'hangul',hangul:'ㅃ',cyrillic:'п'},
            {name:'hangul',hangul:'ㅆ',cyrillic:'с'},
            {name:'hangul',hangul:'ㅉ',cyrillic:'ч'},
            {name:'hangul',hangul:'ㅐ',cyrillic:'э'},
            {name:'hangul',hangul:'ㅒ',cyrillic:'йэ'},
            {name:'hangul',hangul:'ㅔ',cyrillic:'э'},
            {name:'hangul',hangul:'ㅖ',cyrillic:'йэ'},
            {name:'hangul',hangul:'ㅘ',cyrillic:'уа'},
            {name:'hangul',hangul:'ㅙ',cyrillic:'уэ'},
            {name:'hangul',hangul:'ㅚ',cyrillic:'уэ'},
            {name:'hangul',hangul:'ㅝ',cyrillic:'уо'},
            {name:'hangul',hangul:'ㅞ',cyrillic:'уэ'},
            {name:'hangul',hangul:'ㅟ',cyrillic:'уи'},
            {name:'hangul',hangul:'ㅢ',cyrillic:'ыи'},   
    ]},
    {'Финский':[
        {name:'finnish',finnish:'A',cyrillic:'а'},
        {name:'finnish',finnish:'B',cyrillic:'бэ'},
        {name:'finnish',finnish:'C',cyrillic:'сэ'},
        {name:'finnish',finnish:'D',cyrillic:'дэ'},
        {name:'finnish',finnish:'E',cyrillic:'е'},
        {name:'finnish',finnish:'F',cyrillic:'эф'},
        {name:'finnish',finnish:'G',cyrillic:'гэ'},
        {name:'finnish',finnish:'H',cyrillic:'хо'},
        {name:'finnish',finnish:'I',cyrillic:'и'},
        {name:'finnish',finnish:'J',cyrillic:'йи'},
        {name:'finnish',finnish:'K',cyrillic:'ко'},
        {name:'finnish',finnish:'L',cyrillic:'эль'},
        {name:'finnish',finnish:'M',cyrillic:'эм'},
        {name:'finnish',finnish:'N',cyrillic:'эн'},
        {name:'finnish',finnish:'O',cyrillic:'у'},
        {name:'finnish',finnish:'P',cyrillic:'пэ'},
        {name:'finnish',finnish:'Q',cyrillic:'кю'},
        {name:'finnish',finnish:'R',cyrillic:'ар'},
        {name:'finnish',finnish:'S',cyrillic:'эс'},
        {name:'finnish',finnish:'T',cyrillic:'те'},
        {name:'finnish',finnish:'U',cyrillic:'ю'},
        {name:'finnish',finnish:'V',cyrillic:'вэ'},
        {name:'finnish',finnish:'W',cyrillic:'вэ'},
        {name:'finnish',finnish:'X',cyrillic:'экс'},
        {name:'finnish',finnish:'Y',cyrillic:'ы'},
        {name:'finnish',finnish:'Z',cyrillic:'сета'},
        {name:'finnish',finnish:'Å',cyrillic:'о'},
        {name:'finnish',finnish:'Ä',cyrillic:'э'},
        {name:'finnish',finnish:'Ö',cyrillic:'ё'},
    ]},
    {'Сербский':[
        {name:'serbian',serbian:'A',cyrillic:'а'},
        {name:'serbian',serbian:'Б',cyrillic:'б'},
        {name:'serbian',serbian:'В',cyrillic:'в'},
        {name:'serbian',serbian:'Г',cyrillic:'г'},
        {name:'serbian',serbian:'Д',cyrillic:'д'},
        {name:'serbian',serbian:'Ђ',cyrillic:'джь'},
        {name:'serbian',serbian:'Е',cyrillic:'э'},
        {name:'serbian',serbian:'Ж',cyrillic:'ж'},
        {name:'serbian',serbian:'З',cyrillic:'з'},
        {name:'serbian',serbian:'И',cyrillic:'и'},
        {name:'serbian',serbian:'J',cyrillic:'й'},
        {name:'serbian',serbian:'К',cyrillic:'к'},
        {name:'serbian',serbian:'Л',cyrillic:'л'},
        {name:'serbian',serbian:'Љ',cyrillic:'ль'},
        {name:'serbian',serbian:'М',cyrillic:'м'},
        {name:'serbian',serbian:'Н',cyrillic:'н'},
        {name:'serbian',serbian:'Њ',cyrillic:'нь'},
        {name:'serbian',serbian:'О',cyrillic:'о'},
        {name:'serbian',serbian:'П',cyrillic:'п'},
        {name:'serbian',serbian:'Р',cyrillic:'р'},
        {name:'serbian',serbian:'С',cyrillic:'с'},
        {name:'serbian',serbian:'Т',cyrillic:'т'},
        {name:'serbian',serbian:'Ћ',cyrillic:'ч'},
        {name:'serbian',serbian:'У',cyrillic:'у'},
        {name:'serbian',serbian:'Ф',cyrillic:'ф'},
        {name:'serbian',serbian:'Х',cyrillic:'х'},
        {name:'serbian',serbian:'Ц',cyrillic:'ц'},
        {name:'serbian',serbian:'Ч',cyrillic:'ч'},
        {name:'serbian',serbian:'Џ',cyrillic:'дж'},
        {name:'serbian',serbian:'Ш',cyrillic:'ш'},
    ]},
    {'Чешский':[
        {name:'czech',czech:'A',cyrillic:'а'},
        {name:'czech',czech:'Á',cyrillic:'а'},
        {name:'czech',czech:'B',cyrillic:'а'},
        {name:'czech',czech:'C',cyrillic:'а'},
        {name:'czech',czech:'Č',cyrillic:'а'},
        {name:'czech',czech:'D',cyrillic:'а'},
        {name:'czech',czech:'Ď',cyrillic:'а'},
        {name:'czech',czech:'E',cyrillic:'а'},
        {name:'czech',czech:'É',cyrillic:'а'},
        {name:'czech',czech:'F',cyrillic:'а'},
        {name:'czech',czech:'G',cyrillic:'а'},
        {name:'czech',czech:'H',cyrillic:'а'},
        {name:'czech',czech:'CH',cyrillic:'а'},
        {name:'czech',czech:'I',cyrillic:'а'},
        {name:'czech',czech:'Í',cyrillic:'а'},
        {name:'czech',czech:'J',cyrillic:'а'},
        {name:'czech',czech:'K',cyrillic:'а'},
        {name:'czech',czech:'L',cyrillic:'а'},
        {name:'czech',czech:'M',cyrillic:'а'},
        {name:'czech',czech:'N',cyrillic:'а'},
        {name:'czech',czech:'Ň',cyrillic:'а'},
        {name:'czech',czech:'O',cyrillic:'а'},
        {name:'czech',czech:'Ó',cyrillic:'а'},
        {name:'czech',czech:'P',cyrillic:'а'},
        {name:'czech',czech:'Q',cyrillic:'а'},
        {name:'czech',czech:'R',cyrillic:'а'},
        {name:'czech',czech:'Ř',cyrillic:'а'},
        {name:'czech',czech:'S',cyrillic:'а'},
        {name:'czech',czech:'Š',cyrillic:'а'},
        {name:'czech',czech:'T',cyrillic:'а'},
        {name:'czech',czech:'Ť',cyrillic:'а'},
        {name:'czech',czech:'U',cyrillic:'а'},
        {name:'czech',czech:'Ú',cyrillic:'а'},
        {name:'czech',czech:'Ů',cyrillic:'а'},
        {name:'czech',czech:'V',cyrillic:'а'},
        {name:'czech',czech:'W',cyrillic:'а'},
        {name:'czech',czech:'X',cyrillic:'а'},
        {name:'czech',czech:'Y',cyrillic:'а'},
        {name:'czech',czech:'Ý',cyrillic:'а'},
        {name:'czech',czech:'Z',cyrillic:'а'},
        {name:'czech',czech:'Ž',cyrillic:'а'},
        
    ]},
]